### ISSUE TITLE
All links of the site always loads the home page.

### ISSUE THREAD

**Issue by vpadhariya** [mickgeek/yii2-advanced-one-domain-config#15]
Hi mickgeek,

I found your code useful and I am trying to achieve Advanced app project into my hostgator business cloud (shared) account.

for backend I have successfully configured the sub domain however for frontend the hostgator says that I am unable to set this up so I had put the below htaccess rule in public_html direcory.

`Options FollowSymLinks
AddDefaultCharset utf-8

<IfModule mod_rewrite.c>
    RewriteEngine On
    
    # if a directory or a file of the frontend application exists, use the request directly
    RewriteCond %{REQUEST_URI} ^/frontend/web
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # otherwise forward the request to index.php
    RewriteRule . /frontend/web/index.php [L]
    
    # the main rewrite rule for the frontend application
    RewriteCond %{REQUEST_URI} !^/(backend/web|admin)
    RewriteRule !^frontend/web /frontend/web%{REQUEST_URI} [L]

    RewriteCond %{REQUEST_URI} \.(htaccess|htpasswd|svn|git)
    RewriteRule \.(htaccess|htpasswd|svn|git) - [F]
</IfModule>
`

after saving the file it loads the home page successfully but whatever link I click it always keeps opening home page, here is the link: http://cliknpost.com/ visit other links and it will always show the home page content.

Below is my UrlManager configuration.
 `    
'enablePrettyUrl' => true,
'showScriptName'  => false,
`

Your help is much appreciated thanks.

**Comment by mickgeek** [comment]
First of all, look at the log files. Try changing the order of your rule blocks, move the main rewrite rule to the beginning.

I never used the HostGator hosting, but [this help page](http://support.hostgator.com/articles/specialized-help/technical/apache-htaccess/apache-mod_rewrite-and-examples) can be useful.

**Comment by mickgeek** [comment]
No feedback. Closed.

**Comment by vpadhariya** [comment]
Thanks MIckgeek, 

I tried but since Hostgator involved, I finally have to change my primary domain and add the main domain as "addon" domain.
