### ISSUE TITLE
Why don't use Alias in Apache?

### ISSUE THREAD

**Issue by hujuice** [mickgeek/yii2-advanced-one-domain-config#16]
Alias is simpler and quicker.
http://httpd.apache.org/docs/2.4/rewrite/avoid.html#alias
It mange, also, the tedious trailing slash problem.
The resulting configuration is cleaner.
So, why not?

A configuration example below.

Regards,
HUjuice

```
# Frontend
# ==============================
DocumentRoot /path/to/yii2-advanced/frontend/web
<Directory /path/to/yii2-advanced/frontend/web>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted

    # Use mod_rewrite for pretty URL support
    RewriteEngine On
    # If a directory or a file exists, use the request directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # Otherwise forward the request to index.php
    RewriteRule . index.php
</Directory>

# Backend
# ==============================
Alias /backend /path/to/yii2-advanced/backend/web
<Directory /path/to/yii2-advanced/backend/web>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted

    # Use mod_rewrite for pretty URL support
    RewriteEngine On
    # If a directory or a file exists, use the request directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # Otherwise forward the request to index.php
    RewriteRule . index.php
</Directory>
```

**Comment by mickgeek** [comment]
It is not a bug, it is just not the preferred way. Yes, it can be improved.

**Comment by mickgeek** [comment]
I added some improvements to the repository, but I did not add the alias. The access to the `/admin` location (without trailing slash) is important for some sometimes. With the alias we cannot get it.

**Comment by hujuice** [comment]
Apache gives you a trailing slash redirect if the directory is a physical directory, not because Alias: https://httpd.apache.org/docs/2.4/mod/mod_dir.html
Naturally, everyone can prefer its way. Also, Alias can be used in VirtualHost context, but not in directory context (.htaccess).

**Comment by mickgeek** [comment]
Using of the alias ignores other rules above the path and forcibly redirects to the folder (yes, because not a file).
