### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by akudryav** [mickgeek/yii2-advanced-one-domain-config#17]
I use nginx config as it is, /admin location works fine, fronted with page url also,
but home location / (http://advanced.local) gives 404 error! I check in that case no index.php is used6 this is nginx 404 error.
How to fix it?

**Comment by mickgeek** [comment]
Thank you for the report. The latest update added a small error in a regular expression. Try [new config](https://github.com/mickgeek/yii2-advanced-one-domain-config/blob/277a17c5bf2460a9595a8c5023cfe99d3cab21e0/vhosts/nginx.conf).

**Comment by akudryav** [comment]
Yeah, it works fine. Thanks
