### ISSUE TITLE
subdirectory url is not removing

### ISSUE THREAD

**Issue by baltechies** [mickgeek/yii2-advanced-one-domain-config#18]
I tried copied the .htaccess content to root .htaccess file but its showing domain.com/frontend/web/*
in urls

**Comment by mickgeek** [comment]
Hi Bal,

You should carry out [the preparatory work](https://github.com/mickgeek/yii2-advanced-one-domain-config#preparation). The problem is setting the value of the `baseUrl` variable of your configurations.
