### ISSUE TITLE
Combine redirect https rule

### ISSUE THREAD

**Issue by tuannguyent20** [mickgeek/yii2-advanced-one-domain-config#19]
I have a redirect to https rule something like:
RewriteCond %{HTTPS} !=on 
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

How to combine this rule into your .htaccess file without facing the error "redirected too many times"?

**Comment by mickgeek** [comment]
Hello!

Try the next rule: `RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301]`.

**Comment by tuannguyent20** [comment]
Thanks for replying quickly.
I tried the suggested rule right after RewriteEngine on
or appended to the end of .htaccess both with no luck.
Still the error "**mysite.com** redirected you too many times"
If I were moved that rule to vhost conf file, I still got the same error.

**Comment by mickgeek** [comment]
Try add the next lines after `RewriteEngine on`:
```
RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301]
```

**Comment by tuannguyent20** [comment]
RewriteEngine on

RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301]

=> Still the error "mysite.com redirected you too many times"

**Comment by mickgeek** [comment]
Do you tried to clear the cache or test it in another browser?

**Comment by tuannguyent20** [comment]
Yes, I tried to clear the cache on Chrome and FireFox but still no luck.
If I tried redirect to https only without redirect backend + frontend then it worked well.
Only if I combine https redirect with backend + frontend redirections then it would be "mysite.com redirected you too many times. Try clear the cache..." on both Chrome and FireFox with no luck.

**Comment by mickgeek** [comment]
I will try during the week to set the SSL certificate for this application template. If you can solve the problem earlier, write about the results.

**Comment by mickgeek** [comment]
The following works well for me 👌 

`.htaccess`:
```
RewriteEngine on

RewriteCond %{HTTPS} off
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301]
...
```

My virtual host configuration (change `AdvancedLocal` and `advanced.local` on your values):
```
<Macro AdvancedLocal>
    ServerName advanced.local
    DocumentRoot /srv/www/advanced.local

    #ErrorLog /var/log/apache2/advanced.local.error.log
    #CustomLog /var/log/apache2/advanced.local.access.log combined
    LogLevel debug

    <Directory />
        AllowOverride All
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
    </Directory>
</Macro>

<VirtualHost *:80>
    Use AdvancedLocal
</VirtualHost>

<VirtualHost *:443>
    Use AdvancedLocal

    SSLEngine On
    SSLCertificateFile /srv/ssl/advanced.local.crt
    SSLCertificateKeyFile /srv/ssl/advanced.local.key
</VirtualHost>
```

If you got some errors, just run the next commands and restart the Apache server:
```bash
a2enmod macro
a2enmod ssl
```

**Comment by tuannguyent20** [comment]
I forgot to mention I was using WAMP server.
I'll try your suggestion on LAMP server and let you know the result.

**Comment by mickgeek** [comment]
Closed for lack of discussion.
