### ISSUE TITLE
adding a new URI

### ISSUE THREAD

**Issue by yonifine** [mickgeek/yii2-advanced-one-domain-config#2]
First of all thanks for the good work.

I have used your project to isolate my frontend and backend and works great.

my question is what if i need to add a third one with /api that means

localhost - for frontend
localhost/admin for backend
localhost/api for api endpoints

I tried on my own using the /admin as a template but it is not working for me. would be great if you could add this feature in your project.

thanks and regards,

**Comment by dbd5** [comment]
@yonifine,

Take a look at my configuration below and customize accordingly, it has your required third leg for API endpoints. Per common sence and https://httpd.apache.org/docs/2.2/howto/htaccess.html#when, I've chosen not to use .htaccess at all. It works, I hope @mickgeek and other experts can review it for security.

<VirtualHost *:80>

    ServerName awesome.url
    #ErrorLog /dev/null
    #LogLevel emerg
    #CustomLog /dev/null combined

    RewriteEngine on
    # the main rewrite rule for the frontend application
    RewriteCond %{REQUEST_URI} !^/(backend/web|admin)
    RewriteCond %{REQUEST_URI} !^/(endpoints/web|apiv1)
    RewriteRule !^/frontend/web /frontend/web%{REQUEST_URI} [L]
    # redirect to the page without a trailing slash (uncomment if necessary)
    #RewriteCond %{REQUEST_URI} ^/admin/$
    #RewriteRule ^(/admin)/ $1 [L,R=301]
    # disable the trailing slash redirect
    RewriteCond %{REQUEST_URI} ^/admin$
    RewriteRule ^/admin /backend/web/index.php [L]
    RewriteCond %{REQUEST_URI} ^/apiv1$
    RewriteRule ^/apiv1 /endpoints/web/index.php [L]
    
    # the main rewrite rule for the backend application
    RewriteCond %{REQUEST_URI} ^/admin
    RewriteRule ^/admin(.*) /backend/web$1 [L]
	RewriteCond %{REQUEST_URI} ^/apiv1
    RewriteRule ^/apiv1(.*) /endpoints/web$1 [L]

    DocumentRoot /var/www/awesome
    <Directory />
        Options FollowSymLinks
        AllowOverride None
        AddDefaultCharset utf-8
    </Directory>
    <Directory /var/www/awesome/frontend/web>
        RewriteEngine on
        # if a directory or a file exists, use the request directly
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        # otherwise forward the request to index.php
        RewriteRule . index.php

        # use index.php as index file
        DirectoryIndex index.php

        Order Allow,Deny
        Allow from all

        <FilesMatch "\.php$">
            Require all granted
            SetHandler proxy:fcgi://127.0.0.1:9000
                          
        </FilesMatch>
    </Directory>
    <Directory /var/www/awesome/backend/web>
        RewriteEngine on
        # if a directory or a file exists, use the request directly
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        # otherwise forward the request to index.php
        RewriteRule . index.php

        # use index.php as index file
        DirectoryIndex index.php

        Order Allow,Deny
        Allow from all

        <FilesMatch "\.php$">
            Require all granted
            SetHandler proxy:fcgi://127.0.0.1:9000
                                   
        </FilesMatch>
    </Directory>
        <Directory /var/www/awesome/endpoints/web>
        RewriteEngine on
        # if a directory or a file exists, use the request directly
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        # otherwise forward the request to index.php
        RewriteRule . index.php

        # use index.php as index file
        DirectoryIndex index.php

        Order Allow,Deny
        Allow from all

        <FilesMatch "\.php$">
            Require all granted
            SetHandler proxy:fcgi://127.0.0.1:9000
                                   
        </FilesMatch>
    </Directory>
    <FilesMatch \.(htaccess|htpasswd|svn|git)>
        Deny from all
        Satisfy All
    </FilesMatch>
    
	## Logging
  	ErrorLog "/var/log/apache2/av_url_awesome_error.log"
  	ServerSignature Off
  	CustomLog "/var/log/apache2/av_url_awesome_access.log" combined 

  	## SetEnv/SetEnvIf for environment variables
  	SetEnv APP_ENV dev

</VirtualHost>

**Comment by dbd5** [comment]
@All,

There was an error in my former post so I have removed it.
In response to @yonifine, I would suggest the way forward is to create a subdomain of the main domain and map it to the API endpoint via apache. If you need help with this we can work on that.

A

**Comment by mickgeek** [comment]
This problem may occur when using the Nginx config ([a bug ticket](https://trac.nginx.org/nginx/ticket/97)). Try to repeat the alias path in the `try_files` directives:

```nginx
location /api {
    alias $main_root/api/web/;
    try_files $uri /api/api/web/index.php$is_args$args;
    # ...
```

With the current Apache config I cannot reproduce the problem.
