### ISSUE TITLE
Used your settings htaccess etc but not working :(

### ISSUE THREAD

**Issue by bgachip** [mickgeek/yii2-advanced-one-domain-config#20]
See title

If I run php yii serve --port=8890, i can see login page without js and css assets,
if i run php yii serve --docroot="frontend/web/" --port=8890 frontend stuffs working good but /admin i get 404

i dont understand and i tried to put frontend and backend .htaccess but nothing....

I use xampp in windows, pls help meeee

**Comment by mickgeek** [comment]
Hi.

The PHP [built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php) is designed to development purposes. If you want to use it, you can run applications separately without any configurations.

Frontend: `php-fpm php yii serve/index 0.0.0.0:8080 --docroot='@frontend/web'`
Backend: `php-fpm php yii serve/index 0.0.0.0:8080/admin --docroot='@backend/web'`

When using XAMPP, may to use a simple virtual host configuration (see below) and the `.htaccess` file from the repository.

`httpd.conf`:
```
<VirtualHost *:80>
    ServerName 0.0.0.0
    DocumentRoot /xampp/htdocs

    <Directory />
        DirectoryIndex index.html

        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```

May be it will be useful: [Windows FAQ](https://www.apachefriends.org/faq_windows.html) from XAMPP. Sorry for the late answer.
