### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [mickgeek/yii2-advanced-one-domain-config#23]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mickgeek** [comment]
Hi.

Thanks. You can write about a vulnerability here if it exists, just create a new issue.

**Comment by JamieSlome** [comment]
@mickgeek - thanks for your response. Feel free to check out the issue here:

https://huntr.dev/bounties/c717b606-c214-4928-9fba-5588171e7b18/

**Comment by mickgeek** [comment]
Thank you for the report.

In the configuration you can comment the block that prevent the redirect to the address with the trailing slash:
```
location = /admin {
    try_files $uri /backend/web/index.php$is_args$args;
}
```
After it the `/admin` request will be redirect automatically.

Also if you have a big project, follow these recommendations:
- define [the `user` directive](https://nginx.org/en/docs/ngx_core_module.html#user) and use specific permissions to directories and files (e.g. `700 (-rwx------)`);
- separate the frontend and backend parts to different domains.

**Comment by PrplHaz4** [comment]
Is this limited to the included nginx configuration only or is it also present in the apache config?

**Comment by mickgeek** [comment]
If you need to use the `apache.conf` configuration, just comment the below rule:
```
RewriteRule ^/admin$ /admin/ [L,PT]
```

About permissions, any service can execute from any user. See also information about [Suexec](https://httpd.apache.org/docs/2.4/suexec.html).

**Comment by JamieSlome** [comment]
@mickgeek - if possible, are you able to update the status of the [report](https://huntr.dev/bounties/c717b606-c214-4928-9fba-5588171e7b18/)?

**Comment by mickgeek** [comment]
Sorry, I do not have an account on this site.

**Comment by JamieSlome** [comment]
@mickgeek - no worries 👍 Do you have an e-mail I can send a magic URL to? This will allow you to update the report without having to sign-up.

**Comment by mickgeek** [comment]
You can find contacts on the profile page.
