### ISSUE TITLE
Internal server error 500 after making changes

### ISSUE THREAD

**Issue by ravindrakashyap** [mickgeek/yii2-advanced-one-domain-config#4]
HI,
I am getting error 500 as below after changing the files as per your instructions. any help is appreciated.
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

server log:

d 4024:tid 1012] [client ::1:61355] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3590): [client ::1:61355] AH00121: r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /index.php
[Mon Aug 31 00:12:55.626711 2015] [core:debug] [pid 4024:tid 1012] core.c(3596): [client ::1:61355] AH00122: redirected from r->uri = /
[Mon Aug 31 00:15:27.882400 2015] [mpm_winnt:notice] [pid 8140:tid 612] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Mon Aug 31 00:15:27.882400 2015] [mpm_winnt:debug] [pid 4024:tid 508] child.c(1158): AH00357: Child: Exit event signaled. Child process is ending.
[Mon Aug 31 00:15:27.882400 2015] [mpm_winnt:debug] [pid 4024:tid 1036] child.c(735): AH00348: Child: Accept thread exiting.
[Mon Aug 31 00:15:27.882400 2015] [mpm_winnt:debug] [pid 4024:tid 1040] child.c(735): AH00348: Child: Accept thread exiting.
[Mon Aug 31 00:15:28.883461 2015] [mpm_winnt:debug] [pid 4024:tid 508] child.c(1215): AH00359: Child: Released the start mutex
[Mon Aug 31 00:15:28.883461 2015] [mpm_winnt:debug] [pid 4024:tid 508] child.c(1227): AH00361: Child: 64 threads blocked on the completion port
[Mon Aug 31 00:15:29.884642 2015] [mpm_winnt:notice] [pid 4024:tid 508] AH00364: Child: All worker threads have exited.
[Mon Aug 31 00:15:29.888623 2015] [mpm_winnt:debug] [pid 4024:tid 508] mpm_winnt.c(1713): AH00454: Child process is exiting
[Mon Aug 31 00:15:29.920089 2015] [mpm_winnt:notice] [pid 8140:tid 612] AH00430: Parent: Child process 4024 exited successfully.
[Mon Aug 31 00:15:29.921090 2015] [core:info] [pid 8140:tid 612] AH00096: removed PID file C:/Apache24/logs/httpd.pid (pid=8140)
Starting the 'Apache2.4' service
The 'Apache2.4' service is running.

**Comment by mickgeek** [comment]
How the application was configured? With the virtual host or the `.htaccess` file?

**Comment by ravindrakashyap** [comment]
Thanks for responding. I have made changes to both virtual host
(httpd-vhosts.conf) and .htaccess files.

On Mon, Aug 31, 2015 at 3:21 AM, Oleg Belostotskiy <notifications@github.com

**Comment by mickgeek** [comment]
No, it's wrong. You should use one of two ways. Try to remove the `.htaccess` file.

**Comment by ravindrakashyap** [comment]
thanks for the help.

It is throwing same error even after removing .htaccess file.

I could see file structure in my browser when i change the
httpd-vhosts.conf to below,
<VirtualHost *:80>
    DocumentRoot C:/Apache24/htdocs/example/frontend/web
    ServerName www.example.com
</VirtualHost>

**Comment by mickgeek** [comment]
You have an incorrect value of the `DocumentRoot` directive. Change it to `C:/Apache24/htdocs/example` and bring back the `.htaccess` file.

**Comment by ravindrakashyap** [comment]
i corrected it and now i am not seeing the error. but it is not taking me
to home page of the webapp ( index.php) instead  browser is showing the
file structure of the folder...

Index of /
• assets/
• css/
• favicon.ico
• index-test.php
• index.php
• robots.txt

**Comment by mickgeek** [comment]
Try this:

```
<VirtualHost *:80>
    ServerName www.example.com

    DocumentRoot C:/Apache24/htdocs/example
    <Directory />
        AllowOverride All
    </Directory>
</VirtualHost>
```

Or just use [the configuration](https://github.com/mickgeek/yii2-advanced-one-domain-config/blob/master/vhosts/apache.conf) that does not use `.htaccess`.

**Comment by ravindrakashyap** [comment]
It didn't work.

I removed .htaccess from the document root folder and used below virtual
host config, please correct me if i am doing some thing wrong here,

# Virtual Hosts

#

# Required modules: mod_log_config

# If you want to maintain multiple domains/hostnames on your

# machine you can setup VirtualHost containers for them. Most configurations

# use only name-based virtual hosts so the server doesn't need to worry

about

# IP addresses. This is indicated by the asterisks in the directives below.

#

# Please see the documentation at

# URL:http://httpd.apache.org/docs/2.4/vhosts/

# for further details before you try to setup virtual hosts.

#

# You may use the command line option '-S' to verify your virtual host

# configuration.

#

# VirtualHost example:

# Almost any Apache directive may go into a VirtualHost container.

# The first VirtualHost section is used for all requests that do not

# match a ServerName or ServerAlias in any <VirtualHost> block.

#

<VirtualHost *:80>
    DocumentRoot C:/Apache24/htdocs/example
    ServerName www.example.com
RewriteEngine on

```
# the main rewrite rule for the frontend application
RewriteCond %{REQUEST_URI} !^/(backend/web|admin)
RewriteRule !^/frontend/web /frontend/web%{REQUEST_URI} [L]
```

   # redirect to the page without a trailing slash (uncomment if necessary)
    #RewriteCond %{REQUEST_URI} ^/admin/$
    #RewriteRule ^(/admin)/ $1 [L,R=301]

# disable the trailing slash redirect

```
RewriteCond %{REQUEST_URI} ^/admin$
RewriteRule ^/admin /backend/web/index.php [L]
```

   # the main rewrite rule for the backend application
    RewriteCond %{REQUEST_URI} ^/admin
    RewriteRule ^/admin(.*) /backend/web$1 [L]
DocumentRoot C:/Apache24/htdocs/example
    <Directory />
        Options FollowSymLinks
        AllowOverride None
        AddDefaultCharset utf-8
    </Directory>
    <Directory C:/Apache24/htdocs/example/frontend/web>
        RewriteEngine on
        # if a directory or a file exists, use the request directly
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        # otherwise forward the request to index.php
        RewriteRule . index.php

```
    Order Allow,Deny
    Allow from all
</Directory>

<Directory C:/Apache24/htdocs/example/backend/web>
    RewriteEngine on
    # if a directory or a file exists, use the request directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # otherwise forward the request to index.php
    RewriteRule . index.php

    Order Allow,Deny
    Allow from all
</Directory>
<FilesMatch \.(htaccess|htpasswd|svn|git)>
    Deny from all
    Satisfy All
</FilesMatch>
```

</VirtualHost>

On Mon, Aug 31, 2015 at 1:32 PM, Oleg Belostotskiy <notifications@github.com

**Comment by mickgeek** [comment]
I haven't any problems with your configuration. You have the wrong web server settings, I think. Not enough information to understand the reason.

**Comment by ravindrakashyap** [comment]
please find my server settings that i changed for this website setup.
please let me know if you need any more information. thanks for the help.

File Name : httpd.conf

ServerName  127.0.0.1:80

#

# DocumentRoot: The directory out of which you will serve your

# documents. By default, all requests are taken from this directory, but

# symbolic links and aliases may be used to point to other locations.

#
DocumentRoot "c:/Apache24/htdocs/example"
<Directory "c:/Apache24/htdocs/example">
    #
    # Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI
MultiViews
    #
    # Note that "MultiViews" must be named _explicitly_ --- "Options All"
    # doesn't give it to you.
    #
    # The Options directive is both complicated and important.  Please see
    # http://httpd.apache.org/docs/2.4/mod/core.html#options
    # for more information.
    #
    Options Indexes FollowSymLinks

```
#
# AllowOverride controls what directives may be placed in .htaccess
```

files.
    # It can be "All", "None", or any combination of the keywords:
    #   AllowOverride FileInfo AuthConfig Limit
    #
    AllowOverride None

```
#
# Controls who can get stuff from this server.
#
Require all granted
```

</Directory>

File name : hosts
   127.0.0.1        example.com

On Mon, Aug 31, 2015 at 2:26 PM, Oleg Belostotskiy <notifications@github.com

**Comment by mickgeek** [comment]
Hmm, but you don't forget to restart Apache after making changes in the vhost file?

**Comment by ravindrakashyap** [comment]
I restarted apache after chaning vhost file.

On Mon, Aug 31, 2015 at 3:01 PM, Oleg Belostotskiy <notifications@github.com

**Comment by mickgeek** [comment]
Okay, try to change the `AllowOverride` directive to `All` in the Apache config, use the `.htaccess` file, and restart again.

**Comment by ravindrakashyap** [comment]
It didn't work.

On Mon, Aug 31, 2015 at 5:21 PM, Oleg Belostotskiy <notifications@github.com

**Comment by mickgeek** [comment]
I recommend you return to the default configuration and create [the necessary virtual host](https://github.com/mickgeek/yii2-advanced-one-domain-config/blob/master/vhosts/apache.conf), according to [the documentation](http://httpd.apache.org/docs/2.4/vhosts/name-based.html#using). Without any duplicating code! If I understand, now you have two virtual hosts of the one server (in the included `httpd-vhosts.conf` file and `httpd.conf`). Perhaps that's the problem.
