### ISSUE TITLE
how to configure if Yii2 advance template is installed under sub directory of Document root?

### ISSUE THREAD

**Issue by avinashz** [mickgeek/yii2-advanced-one-domain-config#5]
What changes we need to do if Yii2 is setup under sub directory of Document root?

**Comment by mickgeek** [comment]
What exactly doesn't work? Give more information and show the directory hierarchy.

**Comment by avinashz** [comment]
Directory structure is set as below image, highlighted part is my document root, You can see two more directory under doc root and then Yii2 setup. I have made all changes which is mentioned in you repository.

![image](https://cloud.githubusercontent.com/assets/475398/9974743/4e3a245a-5ebd-11e5-8098-6cf9dc54f6c9.png)

**Url :** http://192.168.0.2:36/project/yii-advance/ showing me 404 see below image

![image](https://cloud.githubusercontent.com/assets/475398/9974758/aed734e2-5ebd-11e5-99e3-6a1b7c2616d7.png)

**Url :** http://192.168.0.2:36/project/yii-advance/admin showing me 404 see below image

![image](https://cloud.githubusercontent.com/assets/475398/9974757/a0cae8d0-5ebd-11e5-8fd5-a9490653c2ba.png)

Let me know if any further details required

**Comment by avinashz** [comment]
If I add below line in root htaccess file then it is showing **500 internal server error**.

`RewtiteBase /project/yii-advance/`

**Comment by mickgeek** [comment]
The `RewtiteBase` directive doesn't exist. What you have in the log file of the web server when there is 404?

**Comment by avinashz** [comment]
sorry it was typo. `RewriteBase /project/yii-advance/` also gives me 404 and nothing being logged in my error log file. anything I need to do to enable logging?

Here is my virtual host for your information:

```
# Yii2 Sub Dir
Listen *:36
<Directory "G:\study\yii-subdir">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
<VirtualHost *:36>
    ServerAdmin webmaster@dummy-host2.example.com
    DirectoryIndex index.php index.html
    DocumentRoot "G:\study\yii-subdir"
    ServerName dummy-host2.example.com
    ErrorLog "logs/subdir-error.log"
    #CustomLog "logs/dummy-host2.example.com-access.log" common
</VirtualHost>
```

**Comment by mickgeek** [comment]
Try the following configuration by changing the parameters on your own.

Virtual host:

```
<VirtualHost *:80>
    ServerName yii2.loc

    DocumentRoot "/media/sf_www/deb7apache/docs/yii2.loc"
    <Directory "/">
        DirectoryIndex index.html index.php
        AllowOverride All
    </Directory>
</VirtualHost>
```

yii2.loc/demo/advanced/.htaccess:

```
Options FollowSymLinks
AddDefaultCharset utf-8

<IfModule mod_rewrite.c>
    RewriteEngine On

    # the main rewrite rule for the frontend application
    RewriteCond %{REQUEST_URI} !^/demo/advanced/(frontend/web|backend/web|admin)
    RewriteRule ^(.*) /demo/advanced/frontend/web/$1 [L]

    # redirect to the page without a trailing slash (uncomment if necessary)
    #RewriteCond %{REQUEST_URI} ^/demo/advanced/admin/$
    #RewriteRule ^(admin)/ /demo/advanced/$1 [L,R=301]
    # the main rewrite rule for the backend application
    RewriteCond %{REQUEST_URI} ^/demo/advanced/admin
    RewriteRule ^admin(.*) /demo/advanced/backend/web/$1 [L]

    # if a directory or a file of the frontend application exists, use the request directly
    RewriteCond %{REQUEST_URI} ^/demo/advanced/frontend/web
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # otherwise forward the request to index.php
    RewriteRule . /demo/advanced/frontend/web/index.php [L]

    # if a directory or a file of the backend application exists, use the request directly
    RewriteCond %{REQUEST_URI} ^/demo/advanced/backend/web
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # otherwise forward the request to index.php
    RewriteRule . /demo/advanced/backend/web/index.php [L]

    RewriteCond %{REQUEST_URI} \.(htaccess|htpasswd|svn|git)
    RewriteRule \.(htaccess|htpasswd|svn|git) - [F]
</IfModule>
```

In the frontend configuration file, change the value of the `baseUrl` property to `/demo/advanced`, in the backend - to `/demo/advanced/admin`. And everything else is same as in the manual.

**Comment by avinashz** [comment]
Does above changes works at your end?

I am getting below mentioned errors:

> ( ! ) Warning: require(G:\study\yii-subdir\project\yii-advance\frontend\web/../../common/config/main-local.php): failed to open stream: No such file or directory in G:\study\yii-subdir\project\yii-advance\frontend\web\index.php on line 12
> 
> ( ! ) Fatal error: require(): Failed opening required 'G:\study\yii-subdir\project\yii-advance\frontend\web/../../common/config/main-local.php' (include_path='.;C:\php\pear') in G:\study\yii-subdir\project\yii-advance\frontend\web\index.php on line 12

**Image for reference:**

![image](https://cloud.githubusercontent.com/assets/475398/9980433/4dde76f0-5fb7-11e5-9456-e9d090a57ec5.png)

**Comment by mickgeek** [comment]
Yes, on Debian works fine. Make sure that the application was initialized ([details](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md#preparing-application)).

**Comment by avinashz** [comment]
I have installed using composer so it must be initialized automatically?

**Comment by avinashz** [comment]
@mickgeek not sure but I have tried init for my app and it works. Thanks for all the help. 

**Just thought:** Can we have something which works regardless of structure?

**Comment by mickgeek** [comment]
Installation via Composer (or from the archive file) only copies the data repository. Then you should to prepare the application to run. See the link above.

**Comment by mickgeek** [comment]
I am glad to help.

Create a configuration that would work regardless of a structure is hardly possible. Sysadmins must deal with fine-tuning the server.

**Comment by dbd5** [comment]
@avinashz,

If at all possible, I suggest you make your installation match the exact scenario that this project has been configured for so you can at least get it working to start with.
Thereafter you can start tweaking one setting at a time followed by testing. 
In other words NOT install under sub-directory of documentroot.
Don't be in a hurry to give up on this nice piece of work by @mickgeek 

Adam
