### ISSUE TITLE
add one line in /etc/hosts file for work all...

### ISSUE THREAD

**Issue by paskuale75** [mickgeek/yii2-advanced-one-domain-config#7]
Hi, thanks for great repo/solution :) but on my ubuntu localhost it won't work, 404 return me...

Change this  VirtualHost *:80 ...  to VirtualHost myApp:80

...to make it all work, locally, it would seem that it serves to add this line in /etc/hosts file:

127.0.0.1   myApp

**Comment by mickgeek** [comment]
More often these actions is not necessary. It all depends on the server machine and its network access settings.
