### ISSUE TITLE
Options not allowed here: .htaccess

### ISSUE THREAD

**Issue by kenytux** [mickgeek/yii2-advanced-one-domain-config#8]
I've got this error on my Apache2 log:

/home/kenytux/public_html/mypath/advanced/.htaccess: Options not allowed here, referer: http://advanced/admin/site/login

When i delete the ".htaccess" all work, why?

**Comment by mickgeek** [comment]
What method do you use? If the vhost configuration, you should change [the line `AllowOverride None`](https://github.com/mickgeek/yii2-advanced-one-domain-config/blob/master/vhosts/apache.conf#L24) to `AllowOverride All`. Or if the `.htaccess` file only, try a similar configuration of the base vhost:

```
<VirtualHost *:80>
    ServerName advanced.local
    ServerAlias www.advanced.local

    DocumentRoot /home/kenytux/public_html/mypath/advanced
    <Directory />
        AllowOverride All
    </Directory>
</VirtualHost>
```

**Comment by kenytux** [comment]
It's my fault, i'm not so good in english, :)
I was using the .htaccess and the vhost oups......

**Comment by mickgeek** [comment]
That's all right! :yum:
