### ISSUE TITLE
No longer fully working since nginx 1.8.1

### ISSUE THREAD

**Issue by MariusRumpf** [mickgeek/yii2-advanced-one-domain-config#9]
I use the `vhosts/nginx.conf` file, since upgrading nginx from 1.8.0 to 1.8.1 the page `/admin` downloads the index.php file and does not process it as php any more. Requests to subpages as `/admin/test` work as expected.

The changelog lists the following relevant change:

```
    *) Bugfix: the "try_files" directive inside a nested location given by a
       regular expression worked incorrectly if the "alias" directive was
       used in the outer location.
```

**Comment by mickgeek** [comment]
Thanks!
